pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'MyDockerAccount'
        DOCKERHUB_REPO = 'juanvalenzuela101/calculator_v1_2026'
        DOCKER_IMAGE_TAG = 'latest'
    }
    stages {
        stage('Build Docker Image') {
            steps {
                dir('calculator') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}
