pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn -f junit/testing/pom.xml clean install' // sh for linux and ios
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f junit/testing/pom.xml test'
                
            }
        }
        stage('Code Coverage') {
            steps {
                sh 'mvn -f junit/testing/pom.xml jacoco:report'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }
    }
}
